# Generated by Django 5.1.3 on 2024-12-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
