# Generated by Django 5.1.3 on 2025-01-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publiczone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiczone',
            name='display_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=255, null=True),
        ),
    ]
