# Generated by Django 5.1.3 on 2024-11-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_remove_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
