# Generated by Django 5.1.3 on 2024-11-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_post_like_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
