# Generated by Django 5.1.3 on 2024-11-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_topic_status_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='request_date',
            new_name='joined_at',
        ),
    ]
