# Generated by Django 5.1.3 on 2024-11-26 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.membership'),
        ),
    ]
