# Generated by Django 5.1.3 on 2024-11-26 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_notification_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.membership'),
        ),
    ]
