# Generated by Django 5.1.3 on 2024-11-24 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_random_lookup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='random_lookup',
            new_name='profile',
        ),
    ]
