# Generated by Django 5.1.3 on 2024-12-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
