# Generated by Django 5.1.3 on 2024-11-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_aboutme_account_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='random_lookup',
            field=models.CharField(blank=True, editable=False, max_length=36, unique=True),
        ),
    ]
