# Generated by Django 5.1.3 on 2024-11-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_random_lookup_account_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
