# Generated by Django 5.1.3 on 2024-11-22 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_remove_post_topic_post_subtopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subtopic',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Post Title', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topicDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SubTopic',
        ),
    ]
