# Generated by Django 5.1.3 on 2024-11-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="image",
        ),
        migrations.AddField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="Profile Image"
            ),
        ),
    ]
