# Generated by Django 5.1.3 on 2024-11-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_profile_img_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
