# Generated by Django 5.1.3 on 2024-11-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_profile_img_delete_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_img",
        ),
    ]
