# Generated by Django 5.1.3 on 2024-12-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mychannel", "0002_channellike"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelcomment",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="posts/"),
        ),
        migrations.AddField(
            model_name="channelpost",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
